# Pandas Basics: Investigating Datasets

## Introduction

Pandas is the primary Python library for data manipulation and analysis. It provides tools for:
- Reading and writing data in various formats (CSV, Excel, SQL, etc.)
- Exploring and understanding data structure
- Selecting, filtering, and transforming data
- Computing statistics and summaries

This notebook covers the essential Pandas skills for investigating any dataset. You'll learn how to load data, examine its structure, extract information, and perform basic analysis.

**Learning Objectives:**
1. Read data from CSV files
2. View and understand DataFrame structure
3. Select and access data by rows, columns, and conditions
4. Compute descriptive statistics
5. Get information about data types and missing values

## Part 1: Getting Started with Pandas

### Import Pandas

The standard way to import Pandas is with the alias `pd`. This makes the code concise and follows a community convention.

In [1]:
import pandas as pd
import numpy as np

# Display settings (optional, but helpful)
pd.set_option('display.max_rows', 10)  # Limit rows displayed
pd.set_option('display.max_columns', 10)  # Limit columns displayed

## Part 2: Reading Data from CSV Files

### The `pd.read_csv()` Function

The primary function for loading data is `pd.read_csv()`. It reads comma-separated values from a file and returns a DataFrame—Pandas' fundamental data structure.

**Common parameters:**
- `filepath_or_buffer`: Path to the CSV file
- `delimiter` or `sep`: Character separating values (default is comma)
- `header`: Row number to use as column names (default=0, the first row)
- `names`: Custom column names
- `index_col`: Column to use as row index
- `skiprows`: Number of rows to skip at the start
- `nrows`: Number of rows to read
- `dtype`: Data types for columns
- `parse_dates`: Columns to parse as datetime

### Example: Loading a Dataset

Let's load a sample dataset. We'll use the tornado dataset available in the datasets folder.

In [ ]:
# Load the tornado dataset
df = pd.read_csv('/share/ESCI446/example_datasets/1950-2021_actual_tornadoes.csv')

# If the file has a different delimiter (e.g., tab-separated)
# df = pd.read_csv('path/to/file.csv', delimiter='\t')

print("Dataset loaded successfully!")
print(f"Shape: {df.shape}")

Dataset loaded successfully!
Shape: (67558, 29)

## Part 3: Understanding DataFrame Structure

A DataFrame is a 2D table with:
- **Rows**: Observations or records
- **Columns**: Variables or features
- **Index**: Row labels (usually sequential integers)

### 3.1 View the First Few Rows: `head()`

The `.head()` method displays the first n rows (default=5). This gives you a quick sense of what the data looks like.

In [3]:
# View the first 5 rows
df.head()

# View the first 10 rows
# df.head(10)

    om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
0  192  1950  10   1  1950-10-01  ...   25   0  0   0   0
1  193  1950  10   9  1950-10-09  ...   47   0  0   0   0
2  195  1950  11  20  1950-11-20  ...  177   0  0   0   0
3  196  1950  11  20  1950-11-20  ...  209   0  0   0   0
4  197  1950  11  20  1950-11-20  ...  101   0  0   0   0

[5 rows x 29 columns]

### 3.2 View the Last Few Rows: `tail()`

The `.tail()` method displays the last n rows. Useful for checking recent data or finding patterns near the end of your dataset.

In [4]:
# View the last 5 rows
df.tail()

# View the last 10 rows
# df.tail(10)

           om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
67553  620523  2021   9   8  2021-09-08  ...  109   0  0   0   0
67554  620524  2021   9   8  2021-09-08  ...  109   0  0   0   0
67555  620525  2021   9   8  2021-09-08  ...  129   0  0   0   0
67556  620526  2021   9   9  2021-09-09  ...   13   0  0   0   0
67557  620527  2021   9   9  2021-09-09  ...   37   0  0   0   0

[5 rows x 29 columns]

### 3.3 Get DataFrame Shape: `.shape`

The `.shape` attribute returns a tuple of (number of rows, number of columns). This tells you the size of your dataset.

In [5]:
# Get the number of rows and columns
rows, columns = df.shape
print(f"Number of rows: {rows}")
print(f"Number of columns: {columns}")

Number of rows: 67558
Number of columns: 29

### 3.4 View Column Names: `.columns`

The `.columns` attribute lists all column names. This is essential for knowing which variables are available in your dataset.

In [6]:
# View all column names
print("Column names:")
print(df.columns.tolist())

# Or just display them directly
df.columns

Column names:
['om', 'yr', 'mo', 'dy', 'date', 'time', 'tz', 'st', 'stf', 'stn', 'mag', 'inj', 'fat', 'loss', 'closs', 'slat', 'slon', 'elat', 'elon', 'len', 'wid', 'ns', 'sn', 'sg', 'f1', 'f2', 'f3', 'f4', 'fc']

Index(['om', 'yr', 'mo', 'dy', 'date', 'time', 'tz', 'st', 'stf', 'stn', 'mag',
       'inj', 'fat', 'loss', 'closs', 'slat', 'slon', 'elat', 'elon', 'len',
       'wid', 'ns', 'sn', 'sg', 'f1', 'f2', 'f3', 'f4', 'fc'],
      dtype='object')

### 3.5 Get Data Type Information: `.dtypes` and `.info()`

Data types are crucial—they determine what operations you can perform on columns.

**Common dtypes:**
- `int64`: Integer numbers
- `float64`: Decimal numbers
- `object`: Strings or mixed types
- `bool`: Boolean (True/False)
- `datetime64`: Dates and times
- `category`: Categorical data (limited categories)

The `.dtypes` attribute shows the type of each column. The `.info()` method provides a more detailed summary.

In [7]:
# View data types for each column
print("Data types:")
print(df.dtypes)
print("\n")

# Get detailed information
print("Detailed DataFrame information:")
df.info()

Data types:
om       int64
yr       int64
mo       int64
dy       int64
date    object
         ...
f1       int64
f2       int64
f3       int64
f4       int64
fc       int64
Length: 29, dtype: object


Detailed DataFrame information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67558 entries, 0 to 67557
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   om      67558 non-null  int64
 1   yr      67558 non-null  int64
 2   mo      67558 non-null  int64
 3   dy      67558 non-null  int64
 4   date    67558 non-null  object
 5   time    67558 non-null  object
 6   tz      67558 non-null  int64
 7   st      67558 non-null  object
 8   stf     67558 non-null  int64
 9   stn     67558 non-null  int64
 10  mag     67558 non-null  int64
 11  inj     67558 non-null  int64
 12  fat     67558 non-null  int64
 13  loss    67558 non-null  float64
 14  closs   67558 non-null  float64
 15  slat    67558 non-null  float64
 16  slon    67558 non-null  float64
 17  elat    67558 non-null  float64
 18  elon    67558 non-null  float64
 19  len     67558 non-null  float64
 20  wid     67558 non-null  int64
 21  ns      67558 non-null  int64
 22  sn      67558 non-null  int64
 23  sg      67558 non-null  int64
 24  f1      67558 non-null  int64
 25  f2      67558 non-null  int64
 26  f3      67558 non-null  int64
 27  f4      67558 non-null  int64
 28  fc      67558 non-null  int64
dtypes: float64(7), int64(19), object(3)
memory usage: 14.9+ MB

### 3.6 Get Basic Statistics: `.describe()`

The `.describe()` method provides summary statistics for numerical columns:
- `count`: Non-null values
- `mean`: Average
- `std`: Standard deviation
- `min`: Minimum value
- `25%, 50%, 75%`: Quartiles (percentiles)
- `max`: Maximum value

This gives you a quick overview of the distribution and range of your numerical variables.

In [8]:
# Get summary statistics
df.describe()

# Include all columns (including non-numeric)
# df.describe(include='all')

,om,yr,mo,dy,tz,...,f1,f2,f3,f4,fc
count,67558.000000,67558.000000,67558.000000,67558.000000,67558.000000,...,67558.000000,67558.000000,67558.000000,67558.000000,67558.000000
mean,104588.501983,1991.341618,5.976761,15.921016,3.000977,...,104.714556,8.493709,1.656414,0.508171,0.027576
std,218577.686732,19.330015,2.438192,8.736773,0.072992,...,96.890325,37.758455,16.500175,9.208104,0.163757
min,1.000000,1950.000000,1.000000,1.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000
25%,280.000000,1976.000000,4.000000,8.000000,3.000000,...,37.000000,0.000000,0.000000,0.000000,0.000000
50%,578.000000,1994.000000,6.000000,16.000000,3.000000,...,85.000000,0.000000,0.000000,0.000000,0.000000
75%,1071.000000,2008.000000,7.000000,24.000000,3.000000,...,137.000000,0.000000,0.000000,0.000000,0.000000
max,620937.000000,2021.000000,12.000000,31.000000,9.000000,...,810.000000,810.000000,710.000000,507.000000,1.000000

## Part 4: Selecting and Accessing Data

There are multiple ways to select data from a DataFrame. Choosing the right method depends on what you're trying to access.

### 4.1 Select a Single Column

You can select a column using bracket notation or dot notation. The result is a Series (1D array-like object).

In [17]:
# Method 1: Using brackets (works with any column name)
year_column = df['yr']
print(type(year_column))
print(year_column.head())

# Method 2: Using dot notation (only works if column name is a valid identifier)
# year_column = df.Year
# print(year_column.head())

<class 'pandas.core.series.Series'>
0    1950
1    1950
2    1950
3    1950
4    1950
Name: yr, dtype: int64

### 4.2 Select Multiple Columns

Pass a list of column names to get a new DataFrame with only those columns.

In [19]:
# Select multiple columns
subset = df[['yr', 'mo', 'dy']]
print(type(subset))
subset.head()

<class 'pandas.core.frame.DataFrame'>

     yr  mo  dy
0  1950  10   1
1  1950  10   9
2  1950  11  20
3  1950  11  20
4  1950  11  20

### 4.3 Select Rows by Index: `.iloc[]`

The `.iloc[]` accessor uses integer-location based indexing (like Python lists):
- `df.iloc[row_index]`: Select a single row
- `df.iloc[start:end]`: Select rows by slice (end is exclusive)
- `df.iloc[[i, j, k]]`: Select specific rows by list of indices

In [11]:
# Select the first row (index 0)
print("First row:")
print(df.iloc[0])
print("\n")

# Select rows 0-4 (5 rows total)
print("Rows 0-4:")
print(df.iloc[0:5])
print("\n")

# Select specific rows
print("Rows 0, 2, and 4:")
print(df.iloc[[0, 2, 4]])

First row:
om             192
yr            1950
mo              10
dy               1
date    1950-10-01
           ...
f1              25
f2               0
f3               0
f4               0
fc               0
Name: 0, Length: 29, dtype: object


Rows 0-4:
    om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
0  192  1950  10   1  1950-10-01  ...   25   0  0   0   0
1  193  1950  10   9  1950-10-09  ...   47   0  0   0   0
2  195  1950  11  20  1950-11-20  ...  177   0  0   0   0
3  196  1950  11  20  1950-11-20  ...  209   0  0   0   0
4  197  1950  11  20  1950-11-20  ...  101   0  0   0   0

[5 rows x 29 columns]


Rows 0, 2, and 4:
    om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
0  192  1950  10   1  1950-10-01  ...   25   0  0   0   0
2  195  1950  11  20  1950-11-20  ...  177   0  0   0   0
4  197  1950  11  20  1950-11-20  ...  101   0  0   0   0

[3 rows x 29 columns]

### 4.4 Select Rows by Label: `.loc[]`

The `.loc[]` accessor uses label-based indexing (like dictionaries):
- `df.loc[row_label]`: Select a single row by its index label
- `df.loc[start:end]`: Select rows by label (end is inclusive, unlike iloc)
- `df.loc[condition]`: Select rows matching a condition

In [12]:
# Assume the index is the default integer index (0, 1, 2, ...)
# Select the row with index label 0
print("Row with index 0:")
print(df.loc[0])
print("\n")

# Select rows with index labels 0-4 (both endpoints included)
print("Rows with index 0-4:")
print(df.loc[0:4])

Row with index 0:
om             192
yr            1950
mo              10
dy               1
date    1950-10-01
           ...
f1              25
f2               0
f3               0
f4               0
fc               0
Name: 0, Length: 29, dtype: object


Rows with index 0-4:
    om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
0  192  1950  10   1  1950-10-01  ...   25   0  0   0   0
1  193  1950  10   9  1950-10-09  ...   47   0  0   0   0
2  195  1950  11  20  1950-11-20  ...  177   0  0   0   0
3  196  1950  11  20  1950-11-20  ...  209   0  0   0   0
4  197  1950  11  20  1950-11-20  ...  101   0  0   0   0

[5 rows x 29 columns]

### 4.5 Select Specific Cell: `df.at[]` and `df.iat[]`

To access a specific cell (one value):
- `df.at[row_label, column_name]`: Access by labels
- `df.iat[row_index, column_index]`: Access by integer positions

In [20]:
# Access a specific cell using labels
value = df.at[0, 'yr']
print(f"Year at row 0: {value}")

# Access a specific cell using integer positions
value = df.iat[0, 0]  # First row, first column
print(f"First cell value: {value}")

Year at row 0: 1950
First cell value: 192

### 4.6 Filter Rows Using Conditions

One of the most powerful features: selecting rows that meet specific conditions. Create a boolean mask and pass it to `.loc[]` or use direct indexing.

In [22]:
# Find all tornadoes from a specific year
year_2020 = df[df['yr'] == 2020]
print(f"Number of tornadoes in 2020: {len(year_2020)}")
print(year_2020.head())
print("\n")

# Find tornadoes with casualties above a threshold
high_casualties = df[df['inj'] > 10]
print(f"Number of tornadoes with > 10 injuries: {len(high_casualties)}")
print(high_casualties.head())

Number of tornadoes in 2020: 1082
           om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
65162  619557  2020  10  10  2020-10-10  ...   97   0  0   0   0
65163  619558  2020  10  10  2020-10-10  ...   27   0  0   0   0
65164  619559  2020  10  10  2020-10-10  ...  217   0  0   0   0
65165  619560  2020  10  10  2020-10-10  ...   17   0  0   0   0
65166  619561  2020  10  10  2020-10-10  ...   77   0  0   0   0

[5 rows x 29 columns]


Number of tornadoes with > 10 injuries: 1388
     om    yr  mo  dy        date  ...   f1  f2  f3   f4  fc
7   199  1950  12   2  1950-12-02  ...  119   5   0    0   0
18    9  1950   2  11  1950-02-11  ...  201   0   0    0   0
24   15  1950   2  12  1950-02-12  ...  419   0   0    0   0
27   18  1950   2  12  1950-02-12  ...  419   0   0    0   0
29   20  1950   2  12  1950-02-12  ...   31  17  15  119   0

[5 rows x 29 columns]

### 4.7 Combine Multiple Conditions

Use logical operators (`&` for AND, `|` for OR, `~` for NOT) to combine conditions. Remember to use parentheses around each condition.

In [24]:
# Tornadoes in spring (April-June) with high casualties
spring_months = [4, 5, 6]
high_casualty_spring = df[(df['mo'].isin(spring_months)) & (df['fat'] > 5)]
print(f"High-casualty spring tornadoes: {len(high_casualty_spring)}")
print(high_casualty_spring.head())
print("\n")

# Tornadoes that EITHER occurred before 1960 OR in 2020
old_or_recent = df[(df['yr'] < 1960) | (df['yr'] == 2020)]
print(f"Tornadoes from before 1960 or in 2020: {len(old_or_recent)}")

High-casualty spring tornadoes: 142
      om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
822   90  1953   4  18  1953-04-18  ...    0   0  0   0   0
844  112  1953   4  30  1953-04-30  ...  153   0  0   0   0
875  156  1953   5  10  1953-05-10  ...   47   0  0   0   0
879  160  1953   5  11  1953-05-11  ...  451   0  0   0   0
881  162  1953   5  11  1953-05-11  ...  309   0  0   0   0

[5 rows x 29 columns]


Tornadoes from before 1960 or in 2020: 5875

## Part 5: Descriptive Statistics and Summaries

Pandas provides many methods to compute statistics on your data.

### 5.1 Statistics for Entire DataFrame

In [26]:
# Mean of all numerical columns
print("Mean values:")
print(df.mean(numeric_only=True))
print("\n")

# Sum of all numerical columns
print("Sum of values:")
print(df.sum(numeric_only=True))
print("\n")

# Median
print("Median values:")
print(df.median(numeric_only=True))

Mean values:
om    104588.501983
yr      1991.341618
mo         5.976761
dy        15.921016
tz         3.000977
          ...
f1       104.714556
f2         8.493709
f3         1.656414
f4         0.508171
fc         0.027576
Length: 26, dtype: float64


Sum of values:
om    7.065790e+09
yr    1.345311e+08
mo    4.037780e+05
dy    1.075592e+06
tz    2.027400e+05
          ...
f1    7.074306e+06
f2    5.738180e+05
f3    1.119040e+05
f4    3.433100e+04
fc    1.863000e+03
Length: 26, dtype: float64


Median values:
om     578.0
yr    1994.0
mo       6.0
dy      16.0
tz       3.0
       ...
f1      85.0
f2       0.0
f3       0.0
f4       0.0
fc       0.0
Length: 26, dtype: float64

### 5.2 Statistics for Individual Columns

In [27]:
# Common statistics for a single column
deaths_column = df['fat']

print(f"Mean deaths per tornado: {deaths_column.mean():.2f}")
print(f"Median deaths: {deaths_column.median():.2f}")
print(f"Standard deviation: {deaths_column.std():.2f}")
print(f"Minimum deaths: {deaths_column.min()}")
print(f"Maximum deaths: {deaths_column.max()}")
print(f"Total deaths: {deaths_column.sum()}")

Mean deaths per tornado: 0.09
Median deaths: 0.00
Standard deviation: 1.48
Minimum deaths: 0
Maximum deaths: 158
Total deaths: 6112

### 5.3 Counting and Unique Values

In [29]:
# Count non-null values
print("Count of non-null values:")
print(df.count())
print("\n")

# Count unique values
print("Number of unique values per column:")
print(df.nunique())
print("\n")

# Get unique values for a column
print(f"Unique years: {sorted(df['yr'].unique())}")

Count of non-null values:
om      67558
yr      67558
mo      67558
dy      67558
date    67558
        ...
f1      67558
f2      67558
f3      67558
f4      67558
fc      67558
Length: 29, dtype: int64


Number of unique values per column:
om      14865
yr         72
mo         12
dy         31
date    12300
        ...
f1        285
f2        225
f3        149
f4        112
fc          2
Length: 29, dtype: int64


Unique years: [1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

### 5.4 Value Counts: Distribution of Categorical Data

The `.value_counts()` method shows the frequency of each unique value, useful for understanding categorical variables.

In [30]:
# Count how many tornadoes per month
print("Tornadoes by month:")
print(df['mo'].value_counts().sort_index())
print("\n")

# Most common month (top 5)
print("Top 5 months with most tornadoes:")
print(df['mo'].value_counts().head(5))

Tornadoes by month:
mo
1      1719
2      1945
3      4514
4      9573
5     14818
      ...
8      4788
9      3471
10     2802
11     2647
12     1818
Name: count, Length: 12, dtype: int64


Top 5 months with most tornadoes:
mo
5    14818
6    12492
4     9573
7     6971
8     4788
Name: count, dtype: int64

## Part 6: Handling Missing Data

Real-world datasets often have missing values. It's important to detect and handle them appropriately.

### 6.1 Detect Missing Values

In [31]:
# Check for missing values
print("Missing values per column:")
print(df.isnull().sum())
print("\n")

# Percentage of missing values
print("Percentage of missing values:")
print((df.isnull().sum() / len(df) * 100).round(2))
print("\n")

# Total number of missing values
print(f"Total missing values: {df.isnull().sum().sum()}")

Missing values per column:
om      0
yr      0
mo      0
dy      0
date    0
       ..
f1      0
f2      0
f3      0
f4      0
fc      0
Length: 29, dtype: int64


Percentage of missing values:
om      0.0
yr      0.0
mo      0.0
dy      0.0
date    0.0
       ...
f1      0.0
f2      0.0
f3      0.0
f4      0.0
fc      0.0
Length: 29, dtype: float64


Total missing values: 0

### 6.2 Handle Missing Values

Common strategies:
- **Remove**: Delete rows or columns with missing values
- **Fill**: Replace with a default value (mean, median, forward fill, etc.)
- **Impute**: Use more sophisticated methods

In [32]:
# Remove rows with any missing values
df_no_missing = df.dropna()
print(f"Rows after removing any NaN: {len(df_no_missing)}")
print("\n")

# Remove rows where a specific column is missing
df_deaths_present = df.dropna(subset=['fat'])
print(f"Rows with Deaths data: {len(df_deaths_present)}")
print("\n")

# Fill missing values with a constant
df_filled = df.fillna(0)
print(f"After filling NaN with 0: {df_filled.isnull().sum().sum()} missing values")

Rows after removing any NaN: 67558


Rows with Deaths data: 67558


After filling NaN with 0: 0 missing values

## Part 7: Practical Investigation Workflow

Here's a typical workflow for investigating a new dataset:

1. Load the data
2. Check shape and basic info
3. View sample rows
4. Examine data types and missing values
5. Compute summary statistics
6. Explore relationships with filtering and grouping

Let's apply this to our tornado dataset:

In [33]:
# Step 1: Overview
print("=== DATASET OVERVIEW ===")
print(f"Shape: {df.shape}")
print(f"\nFirst few rows:")
print(df.head())

=== DATASET OVERVIEW ===
Shape: (67558, 29)

First few rows:
    om    yr  mo  dy        date  ...   f1  f2 f3  f4  fc
0  192  1950  10   1  1950-10-01  ...   25   0  0   0   0
1  193  1950  10   9  1950-10-09  ...   47   0  0   0   0
2  195  1950  11  20  1950-11-20  ...  177   0  0   0   0
3  196  1950  11  20  1950-11-20  ...  209   0  0   0   0
4  197  1950  11  20  1950-11-20  ...  101   0  0   0   0

[5 rows x 29 columns]

In [34]:
# Step 2: Data types and info
print("=== DATA TYPES AND INFO ===")
df.info()

=== DATA TYPES AND INFO ===
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67558 entries, 0 to 67557
Data columns (total 29 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   om      67558 non-null  int64
 1   yr      67558 non-null  int64
 2   mo      67558 non-null  int64
 3   dy      67558 non-null  int64
 4   date    67558 non-null  object
 5   time    67558 non-null  object
 6   tz      67558 non-null  int64
 7   st      67558 non-null  object
 8   stf     67558 non-null  int64
 9   stn     67558 non-null  int64
 10  mag     67558 non-null  int64
 11  inj     67558 non-null  int64
 12  fat     67558 non-null  int64
 13  loss    67558 non-null  float64
 14  closs   67558 non-null  float64
 15  slat    67558 non-null  float64
 16  slon    67558 non-null  float64
 17  elat    67558 non-null  float64
 18  elon    67558 non-null  float64
 19  len     67558 non-null  float64
 20  wid     67558 non-null  int64
 21  ns      67558 non-null  int64
 22  sn      67558 non-null  int64
 23  sg      67558 non-null  int64
 24  f1      67558 non-null  int64
 25  f2      67558 non-null  int64
 26  f3      67558 non-null  int64
 27  f4      67558 non-null  int64
 28  fc      67558 non-null  int64
dtypes: float64(7), int64(19), object(3)
memory usage: 14.9+ MB

In [35]:
# Step 3: Missing data
print("=== MISSING VALUES ===")
missing_summary = pd.DataFrame({
    'Column': df.columns,
    'Missing_Count': df.isnull().sum(),
    'Missing_Percent': (df.isnull().sum() / len(df) * 100).round(2)
})
print(missing_summary[missing_summary['Missing_Count'] > 0])

=== MISSING VALUES ===
Empty DataFrame
Columns: [Column, Missing_Count, Missing_Percent]
Index: []

In [36]:
# Step 4: Summary statistics
print("=== SUMMARY STATISTICS ===")
print(df.describe())

=== SUMMARY STATISTICS ===
                  om            yr            mo            dy            tz  \
count   67558.000000  67558.000000  67558.000000  67558.000000  67558.000000
mean   104588.501983   1991.341618      5.976761     15.921016      3.000977
std    218577.686732     19.330015      2.438192      8.736773      0.072992
min         1.000000   1950.000000      1.000000      1.000000      0.000000
25%       280.000000   1976.000000      4.000000      8.000000      3.000000
50%       578.000000   1994.000000      6.000000     16.000000      3.000000
75%      1071.000000   2008.000000      7.000000     24.000000      3.000000
max    620937.000000   2021.000000     12.000000     31.000000      9.000000

       ...            f1            f2            f3            f4  \
count  ...  67558.000000  67558.000000  67558.000000  67558.000000
mean   ...    104.714556      8.493709      1.656414      0.508171
std    ...     96.890325     37.758455     16.500175      9.208104
min    ...      0.000000      0.000000      0.000000      0.000000
25%    ...     37.000000      0.000000      0.000000      0.000000
50%    ...     85.000000      0.000000      0.000000      0.000000
75%    ...    137.000000      0.000000      0.000000      0.000000
max    ...    810.000000    810.000000    710.000000    507.000000

                 fc
count  67558.000000
mean       0.027576
std        0.163757
min        0.000000
25%        0.000000
50%        0.000000
75%        0.000000
max        1.000000

[8 rows x 26 columns]

In [38]:
# Step 5: Explore key questions
print("=== EXPLORATORY QUESTIONS ===")
print(f"Time range: {df['yr'].min()} to {df['yr'].max()}")
print(f"\nMost deadly tornado: {df['fat'].max()} deaths")
print(f"Total deaths in dataset: {df['fat'].sum()}")
print(f"\nAverage deaths per tornado: {df['fat'].mean():.2f}")
print(f"\nTornadoes by decade:")
df['Decade'] = (df['yr'] // 10 * 10).astype(str) + 's'
print(df['Decade'].value_counts().sort_index())

=== EXPLORATORY QUESTIONS ===
Time range: 1950 to 2021

Most deadly tornado: 158 deaths
Total deaths in dataset: 6112

Average deaths per tornado: 0.09

Tornadoes by decade:
Decade
1950s     4793
1960s     6811
1970s     8579
1980s     8195
1990s    12137
2000s    12721
2010s    11926
2020s     2396
Name: count, dtype: int64

## Part 8: Quick Reference Guide

### Loading Data
```python
df = pd.read_csv('file.csv')
df = pd.read_csv('file.csv', delimiter='\t')  # Tab-separated
df = pd.read_csv('file.csv', parse_dates=['date_column'])
```

### Viewing Data
```python
df.head()           # First 5 rows
df.tail(10)         # Last 10 rows
df.shape            # (rows, columns)
df.columns          # Column names
df.dtypes           # Data types
df.info()           # Detailed info
```

### Selecting Data
```python
df['column']        # Single column
df[['col1', 'col2']] # Multiple columns
df.iloc[0:5]        # First 5 rows by position
df.loc[0:4]         # Rows with index 0-4 (inclusive)
df[df['col'] > 10]  # Rows where col > 10
df.at[0, 'col']     # Single value by label
df.iat[0, 0]        # Single value by position
```

### Statistics
```python
df.describe()       # Summary statistics
df.mean()           # Mean of each column
df['col'].mean()    # Mean of one column
df['col'].sum()     # Sum
df['col'].min()     # Minimum
df['col'].max()     # Maximum
df['col'].std()     # Standard deviation
df['col'].count()   # Count non-null values
df['col'].unique()  # Unique values
df['col'].value_counts()  # Frequency table
```

### Missing Data
```python
df.isnull().sum()   # Count missing values
df.dropna()         # Remove rows with NaN
df.fillna(0)        # Replace NaN with 0
df.fillna(df.mean()) # Replace with column mean
```

## Summary

You've learned the fundamental skills for investigating datasets with Pandas:

✓ **Reading data** from CSV files  
✓ **Understanding structure** (shape, columns, dtypes)  
✓ **Selecting data** by rows, columns, and conditions  
✓ **Computing statistics** to summarize your data  
✓ **Handling missing values** appropriately  

These skills form the foundation for all data analysis work. Practice them repeatedly, and soon you'll be able to quickly investigate any dataset with confidence!